server:
  port: 8080
  servlet:
    context-path: /pet-api

# 文件上传配置
upload:
  path: D:/upload

# 数据库配置（改自己的账号密码）
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_manage?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root  # 你的MySQL账号
    password: 123456  # 你的MySQL密码

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:mapper/*.xml